version: '3.1'
services:
    php:
        build: ./two_factor_authenticator
    web:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/log:/var/log/nginx
        depends_on:
            - php
    client:
        build: ./client
        ports:
            - "8081:80"
