version: '3.1'
services:
    php:
        build: ./.docker/php
        volumes:
            - ./two_factor_authenticator-v4:/var/www
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    web:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./two_factor_authenticator-v4:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/log:/var/log/nginx
        depends_on:
            - php
    client:
        build: ./client
        ports:
            - "8081:80"
